spring:
  datasource:
    url: jdbc:h2:file:~/agilemonkeysshop
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    initialize: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher